name: mush_room
description: This project have name Mush Room
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  intl_translation: ^0.18.2
  get_it: ^7.0.0
  shared_preferences: ^2.0.8
  logger: ^1.1.0
  dio: ^4.0.0
  flutter_svg: ^1.1.6
  qr_code_scanner: ^1.0.1

  # The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  # Automatically adapt UI to different screen sizes. Responsiveness made simple.
  sizer: ^2.0.15
  # Loading animation or loading spiner or loader.
  # It's used to show loading animation when the app is in loading state or something is processing for uncertain time.
  loading_animation_widget: ^1.2.0+4

  # A Flutter package to use fonts from fonts.google.com. Supports HTTP fetching, caching, and asset bundling.
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/svgs/
    - assets/images/
    # File font
    - assets/google_fonts/
