name: mush_room
description: This project have name Mush Room
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  intl_translation: ^0.18.2
  get_it: ^7.0.0
  shared_preferences: ^2.0.8
  logger: ^1.1.0
  dio: ^4.0.0
  flutter_svg: ^1.1.6
  qr_code_scanner: ^1.0.1
  wifi_iot: ^0.3.18+1
  connectivity: ^3.0.6
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  permission_handler: ^10.2.0
  sizer: ^2.0.15
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^6.1.0
  jwt_decode: ^0.3.1
  youtube_player_flutter: ^8.1.2

  # A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
  mqtt_client: ^9.6.8

  #firebase
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/svgs/
    - assets/images/
    # File certificate server mqtt
    - assets/mqtt/AmazonRootCA1.pem
    - assets/mqtt/bea8-certificate.pem.crt
    - assets/mqtt/bea8-private.pem.key
