name: mush_room
description: This project have name Mush Room
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  intl_translation: ^0.18.2
  get_it: ^7.0.0
  shared_preferences: ^2.0.8
  logger: ^1.1.0
  dio: ^4.0.0
  flutter_svg: ^1.1.6
  qr_code_scanner: ^1.0.1
  wifi_iot: ^0.3.18+1
  connectivity: ^3.0.6
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  permission_handler: ^10.2.0
  sizer: ^2.0.15
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^6.1.0
  jwt_decode: ^0.3.1
#  flutter_native_splash: ^2.3.4
#
#flutter_native_splash:
#  color: "#ffffff"
#  image: assets/icons/icon_splash.png
#  branding: assets/icons/icon_splash.png
#  color_dark: "#121212"
#  image_dark: assets/icons/icon_splash.png
#  branding_dark: assets/icons/icon_splash.png
#
#  android_12:
#    image: assets/icons/icon_splash.png
#    icon_background_color: "#ffffff"
#    image_dark: assets/icons/icon_splash.png
#    icon_background_color_dark: "#121212"
#
#  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/svgs/
    - assets/images/
